// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnML10LMqcWv6xK-m1-eJFviuFPXv1gSo',
    appId: '1:267447834561:web:3940e403d0377a7516c140',
    messagingSenderId: '267447834561',
    projectId: 'medibook-641dd',
    authDomain: 'medibook-641dd.firebaseapp.com',
    storageBucket: 'medibook-641dd.firebasestorage.app',
    measurementId: 'G-ZNBPNF31L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh1cjSwUWk7yd329GQI923wO_wW36GJPM',
    appId: '1:267447834561:android:8d024a9fc284bbc316c140',
    messagingSenderId: '267447834561',
    projectId: 'medibook-641dd',
    storageBucket: 'medibook-641dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9AQ5mGwTWzsAo_UbCF699tmtxXBTv-ZI',
    appId: '1:267447834561:ios:2a3e133d4ca2489116c140',
    messagingSenderId: '267447834561',
    projectId: 'medibook-641dd',
    storageBucket: 'medibook-641dd.firebasestorage.app',
    iosBundleId: 'com.medibook.medibookMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9AQ5mGwTWzsAo_UbCF699tmtxXBTv-ZI',
    appId: '1:267447834561:ios:2a3e133d4ca2489116c140',
    messagingSenderId: '267447834561',
    projectId: 'medibook-641dd',
    storageBucket: 'medibook-641dd.firebasestorage.app',
    iosBundleId: 'com.medibook.medibookMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnML10LMqcWv6xK-m1-eJFviuFPXv1gSo',
    appId: '1:267447834561:web:14eba8a92989d86116c140',
    messagingSenderId: '267447834561',
    projectId: 'medibook-641dd',
    authDomain: 'medibook-641dd.firebaseapp.com',
    storageBucket: 'medibook-641dd.firebasestorage.app',
    measurementId: 'G-CPPVR3GZJK',
  );
}
