import 'translation_keys.dart';

const Map<String, String> en = {
  // General
  Tr.appName: 'MediBook',
  Tr.tagline: 'Your health, our priority',
  Tr.error: 'Error',
  Tr.confirm: 'Confirm',
  Tr.yes: 'Yes',
  Tr.no: 'No',
  Tr.cancel: 'Cancel',
  Tr.name: 'Name',
  Tr.information: 'Information',
  Tr.notSpecified: 'Not specified',
  Tr.notifications: 'Notifications',

  // Auth
  Tr.login: 'Login',
  Tr.email: 'Email',
  Tr.password: 'Password',
  Tr.connect: 'Sign in',
  Tr.welcome: 'Welcome!',
  Tr.welcomeSubtitle: 'Sign in to book\nyour medical appointments',
  Tr.testAccount: 'Test account:\nfatou.sall@email.com / 123456',
  Tr.fillAllFields: 'Please fill in all fields',
  Tr.loginSuccess: 'Login successful',
  Tr.register: 'Register',
  Tr.firstName: 'First name',
  Tr.lastName: 'Last name',
  Tr.phoneNumber: 'Phone number',
  Tr.confirmPassword: 'Confirm password',
  Tr.createAccount: 'Create account',
  Tr.alreadyHaveAccount: 'Already have an account?',
  Tr.noAccount: 'Don\'t have an account?',
  Tr.registerSuccess: 'Registration successful',
  Tr.passwordMismatch: 'Passwords do not match',
  Tr.loginFailed: 'Invalid email or password',
  Tr.connectionError: 'Unable to connect to the server',
  Tr.registerError: 'Registration error',
  Tr.disconnectConfirm: 'Are you sure you want to logout?',
  Tr.disconnect: 'Logout',

  // Navigation
  Tr.home: 'Home',
  Tr.appointments: 'Appointments',
  Tr.search: 'Search',
  Tr.profile: 'Profile',

  // Home
  Tr.hello: 'Hello',
  Tr.howAreYou: 'How are you today?',
  Tr.searchDoctorSpecialty: 'Search a doctor, specialty...',
  Tr.searchDoctorCabinet: 'Search a doctor, cabinet...',
  Tr.nextAppointment: 'Next appointment',
  Tr.seeAll: 'See all',
  Tr.quickAccess: 'Quick access',
  Tr.myProfile: 'My profile',
  Tr.myAppointments: 'My appointments',
  Tr.settings: 'Settings',
  Tr.logout: 'Logout',

  // Cabinets
  Tr.cabinets: 'Cabinets',
  Tr.medicalCabinets: 'Medical cabinets',
  Tr.cabinet: 'Cabinet',
  Tr.findNearby: 'Find a nearby cabinet',
  Tr.noCabinets: 'No cabinets found',
  Tr.comeBackLater: 'Come back later',
  Tr.address: 'Address',
  Tr.phone: 'Phone',

  // Specialties
  Tr.specialties: 'Specialties',
  Tr.browseBySpecialty: 'Browse by specialty',
  Tr.noSpecialties: 'No specialties found',

  // Doctors
  Tr.doctors: 'Doctors',
  Tr.doctor: 'Doctor',
  Tr.allAvailableDoctors: 'All available doctors',
  Tr.noDoctors: 'No doctors found',
  Tr.tryAnotherFilter: 'Try another filter',
  Tr.seeDoctors: 'See doctors',

  // Booking
  Tr.book: 'Book',
  Tr.chooseDate: 'Choose a date',
  Tr.availableSlots: 'Available slots',
  Tr.selectDate: 'Select a date',
  Tr.selectSlot: 'Select a time slot',
  Tr.selectSlotError: 'Please select a time slot',
  Tr.enterReasonError: 'Please enter a reason for consultation',
  Tr.consultationReason: 'Reason for consultation',
  Tr.describeReason: 'Describe the reason for your consultation...',
  Tr.reasonHint: 'Reason for consultation',
  Tr.confirmBooking: 'Confirm booking',
  Tr.confirmAppointment: 'Confirm appointment',
  Tr.bookingSuccess: 'Appointment booked successfully!',
  Tr.appointmentConfirmed: 'Appointment confirmed!',
  Tr.appointmentConfirmedMsg: 'Your appointment has been booked successfully',
  Tr.noSlots: 'No available slots',
  Tr.tryAnotherDate: 'Try another date',

  // Appointments
  Tr.all: 'All',
  Tr.pending: 'Pending',
  Tr.confirmed: 'Confirmed',
  Tr.history: 'History',
  Tr.date: 'Date',
  Tr.time: 'Time',
  Tr.reason: 'Reason',
  Tr.status: 'Status',
  Tr.appointmentDetails: 'Appointment details',
  Tr.noAppointments: 'No appointments',
  Tr.bookFirstAppointment: 'Book your first appointment!',
  Tr.cancelAppointment: 'Cancel appointment',
  Tr.cancelConfirm: 'Are you sure you want to cancel this appointment?',
  Tr.cancelIrreversible: 'Are you sure you want to cancel this appointment? This action is irreversible.',
  Tr.cancelRdv: 'Cancel appointment',
  Tr.noKeep: 'No, keep it',
  Tr.yesCancel: 'Yes, cancel',
  Tr.appointmentCancelled: 'Appointment cancelled',
  Tr.appointmentCancelledMsg: 'The appointment has been cancelled successfully',
  Tr.appointmentCancelledText: 'This appointment has been cancelled',
  Tr.appointmentNotFound: 'Appointment not found',
  Tr.dateAndTime: 'Date & Time',

  // Status labels
  Tr.statusPending: 'Pending',
  Tr.statusConfirmed: 'Confirmed',
  Tr.statusCompleted: 'Completed',
  Tr.statusCancelled: 'Cancelled',

  // Profile
  Tr.editProfile: 'Edit profile',
  Tr.save: 'Save',
  Tr.success: 'Success',
  Tr.profileUpdated: 'Profile updated successfully',
  Tr.profileUpdateError: 'Error updating profile',

  // Error messages (viewmodels)
  Tr.loadingError: 'Loading error',
  Tr.loadingCabinetsError: 'Error loading cabinets',
  Tr.loadingSpecialtiesError: 'Error loading specialties',
  Tr.loadingDoctorsError: 'Error loading doctors',
  Tr.loadingDoctorError: 'Error loading doctor',
  Tr.loadingSlotsError: 'Error loading available slots',
  Tr.loadingAppointmentsError: 'Error loading appointments',
  Tr.createAppointmentError: 'Error creating appointment',
  Tr.cancelAppointmentError: 'Error cancelling appointment',
  Tr.noResults: 'No results',
  Tr.allFilter: 'All',
};
