import 'translation_keys.dart';

const Map<String, String> fr = {
  // General
  Tr.appName: 'MediBook',
  Tr.tagline: 'Votre santé, notre priorité',
  Tr.error: 'Erreur',
  Tr.confirm: 'Confirmer',
  Tr.yes: 'Oui',
  Tr.no: 'Non',
  Tr.cancel: 'Annuler',
  Tr.name: 'Nom',
  Tr.information: 'Informations',
  Tr.notSpecified: 'Non spécifié',
  Tr.notifications: 'Notifications',

  // Auth
  Tr.login: 'Connexion',
  Tr.email: 'Email',
  Tr.password: 'Mot de passe',
  Tr.connect: 'Se connecter',
  Tr.welcome: 'Bienvenue !',
  Tr.welcomeSubtitle: 'Connectez-vous pour prendre\nvos rendez-vous médicaux',
  Tr.testAccount: 'Compte test :\nfatou.sall@email.com / 123456',
  Tr.fillAllFields: 'Veuillez remplir tous les champs',
  Tr.loginSuccess: 'Connexion réussie',
  Tr.register: 'Inscription',
  Tr.firstName: 'Prénom',
  Tr.lastName: 'Nom',
  Tr.phoneNumber: 'Téléphone',
  Tr.confirmPassword: 'Confirmer le mot de passe',
  Tr.createAccount: 'Créer un compte',
  Tr.alreadyHaveAccount: 'Vous avez déjà un compte ?',
  Tr.noAccount: 'Pas encore de compte ?',
  Tr.registerSuccess: 'Inscription réussie',
  Tr.passwordMismatch: 'Les mots de passe ne correspondent pas',
  Tr.disconnectConfirm: 'Êtes-vous sûr de vouloir vous déconnecter ?',
  Tr.disconnect: 'Déconnexion',

  // Navigation
  Tr.home: 'Accueil',
  Tr.appointments: 'Rendez-vous',
  Tr.search: 'Recherche',
  Tr.profile: 'Profil',

  // Home
  Tr.hello: 'Bonjour',
  Tr.howAreYou: 'Comment allez-vous aujourd\'hui ?',
  Tr.searchDoctorSpecialty: 'Rechercher un médecin, spécialité...',
  Tr.searchDoctorCabinet: 'Rechercher un médecin, cabinet...',
  Tr.nextAppointment: 'Prochain rendez-vous',
  Tr.seeAll: 'Voir tout',
  Tr.quickAccess: 'Accès rapide',
  Tr.myProfile: 'Mon profil',
  Tr.myAppointments: 'Mes rendez-vous',
  Tr.settings: 'Paramètres',
  Tr.logout: 'Se déconnecter',

  // Cabinets
  Tr.cabinets: 'Cabinets',
  Tr.medicalCabinets: 'Cabinets médicaux',
  Tr.cabinet: 'Cabinet',
  Tr.findNearby: 'Trouver un cabinet proche',
  Tr.noCabinets: 'Aucun cabinet trouvé',
  Tr.comeBackLater: 'Revenez plus tard',
  Tr.address: 'Adresse',
  Tr.phone: 'Téléphone',

  // Specialties
  Tr.specialties: 'Spécialités',
  Tr.browseBySpecialty: 'Parcourir par spécialité',
  Tr.noSpecialties: 'Aucune spécialité trouvée',

  // Doctors
  Tr.doctors: 'Médecins',
  Tr.doctor: 'Médecin',
  Tr.allAvailableDoctors: 'Tous les médecins disponibles',
  Tr.noDoctors: 'Aucun médecin trouvé',
  Tr.tryAnotherFilter: 'Essayez un autre filtre',
  Tr.seeDoctors: 'Voir les médecins',

  // Booking
  Tr.book: 'Réserver',
  Tr.chooseDate: 'Choisir une date',
  Tr.availableSlots: 'Créneaux disponibles',
  Tr.selectDate: 'Sélectionnez une date',
  Tr.selectSlot: 'Sélectionnez un créneau',
  Tr.selectSlotError: 'Veuillez sélectionner un créneau',
  Tr.enterReasonError: 'Veuillez saisir un motif de consultation',
  Tr.consultationReason: 'Motif de consultation',
  Tr.describeReason: 'Décrivez le motif de votre consultation...',
  Tr.reasonHint: 'Motif de la consultation',
  Tr.confirmBooking: 'Confirmer la réservation',
  Tr.confirmAppointment: 'Confirmer le rendez-vous',
  Tr.bookingSuccess: 'Rendez-vous réservé avec succès !',
  Tr.appointmentConfirmed: 'Rendez-vous confirmé !',
  Tr.appointmentConfirmedMsg: 'Votre rendez-vous a été pris avec succès',
  Tr.noSlots: 'Aucun créneau disponible',
  Tr.tryAnotherDate: 'Essayez une autre date',

  // Appointments
  Tr.all: 'Tous',
  Tr.pending: 'En attente',
  Tr.confirmed: 'Confirmés',
  Tr.history: 'Historique',
  Tr.date: 'Date',
  Tr.time: 'Heure',
  Tr.reason: 'Motif',
  Tr.status: 'Statut',
  Tr.appointmentDetails: 'Détails du rendez-vous',
  Tr.noAppointments: 'Aucun rendez-vous',
  Tr.bookFirstAppointment: 'Prenez votre premier rendez-vous !',
  Tr.cancelAppointment: 'Annuler le rendez-vous',
  Tr.cancelConfirm: 'Êtes-vous sûr de vouloir annuler ce rendez-vous ?',
  Tr.cancelIrreversible: 'Êtes-vous sûr de vouloir annuler ce rendez-vous ? Cette action est irréversible.',
  Tr.cancelRdv: 'Annuler le RDV',
  Tr.noKeep: 'Non, garder',
  Tr.yesCancel: 'Oui, annuler',
  Tr.appointmentCancelled: 'Rendez-vous annulé',
  Tr.appointmentCancelledMsg: 'Le rendez-vous a été annulé avec succès',
  Tr.appointmentCancelledText: 'Ce rendez-vous a été annulé',
  Tr.appointmentNotFound: 'Rendez-vous non trouvé',
  Tr.dateAndTime: 'Date & Heure',

  // Status labels
  Tr.statusPending: 'En attente',
  Tr.statusConfirmed: 'Confirmé',
  Tr.statusCompleted: 'Terminé',
  Tr.statusCancelled: 'Annulé',
};
